// apps/react-app/src/app/app.tsx
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import styles from './app.module.scss';
import { MyComponent } from  '@nx-workspace/web-component-react'; 

import NxWelcome from './nx-welcome';

export function App() {
  return (
    <div>
      <MyComponent first='Kyyba' middle='Tech' last='India'></MyComponent>
      <NxWelcome title="react-app" />
    </div>
  );
}

export default App;

// apps/angular-app/src/app/app.component.ts
import { Component } from '@angular/core';
import { RouterModule } from '@angular/router';
import { NxWelcomeComponent } from './nx-welcome.component';
import { WebComponentAngularModule } from '@nx-workspace/web-component-angular';

@Component({
  standalone: true,
  imports: [NxWelcomeComponent, RouterModule, WebComponentAngularModule],
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrl: './app.component.scss',
})
export class AppComponent {
  title = 'angular-app';
}

<app-nx-welcome>
</app-nx-welcome> 
<router-outlet>
</router-outlet>
<my-component first="Kyyba" middle="Tech" last="India"></my-component>
